// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWKgaXGsj_BIjGt50yZf6f0IYRRqdkcuk',
    appId: '1:229715153190:web:ce880c789430c702e9f1e7',
    messagingSenderId: '229715153190',
    projectId: 'grid-ev-station',
    authDomain: 'grid-ev-station.firebaseapp.com',
    storageBucket: 'grid-ev-station.appspot.com',
    measurementId: 'G-J0Q1ZJB926',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn6o_eNFkfZx4rECrAYg8CuccRmIses4U',
    appId: '1:229715153190:android:5401ef04bfcfb8cae9f1e7',
    messagingSenderId: '229715153190',
    projectId: 'grid-ev-station',
    storageBucket: 'grid-ev-station.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0TYchp7aSF0dGta2ZCMEyVr4V6mBA-dg',
    appId: '1:229715153190:ios:f00a0549a9c7e7c2e9f1e7',
    messagingSenderId: '229715153190',
    projectId: 'grid-ev-station',
    storageBucket: 'grid-ev-station.appspot.com',
    iosClientId: '229715153190-v4g4h7ar3aqj7q7qlv1ucef3nteiiid1.apps.googleusercontent.com',
    iosBundleId: 'com.bireka.grid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0TYchp7aSF0dGta2ZCMEyVr4V6mBA-dg',
    appId: '1:229715153190:ios:d18abda496c967cee9f1e7',
    messagingSenderId: '229715153190',
    projectId: 'grid-ev-station',
    storageBucket: 'grid-ev-station.appspot.com',
    iosClientId: '229715153190-l3in9ik46kc5pu6e8hk0ont0703mi9qp.apps.googleusercontent.com',
    iosBundleId: 'com.bireka.grid.RunnerTests',
  );
}
